---

version: '2'

services:
  sql-database:
    image: registry.hub.docker.com/library/mariadb:latest
    volumes:
      - sql-database:/var/lib/mysql/
    ports:
      - 127.0.0.1:3306:3306
    env_file: ./env
    restart: always

volumes:
  sql-database:
