---

version: '2'

services:
  mail-service:
    build:
      context: .
      dockerfile: ./docker/mail-service/Dockerfile
    env_file: ./docker/mail-service/env
    ports:
      - 127.0.0.1:8081:8081
    restart: always
  user-service:
    build:
      context: .
      dockerfile: ./docker/user-service/Dockerfile
    env_file: ./docker/user-service/env
    ports:
      - 127.0.0.1:8082:8082
    restart: always
  httpcheck-service:
    build:
      context: .
      dockerfile: ./docker/httpcheck-service/Dockerfile
    env_file: ./docker/httpcheck-service/env
    ports:
      - 127.0.0.1:8083:8083
    restart: always
  alert-service:
    build:
      context: .
      dockerfile: ./docker/alert-service/Dockerfile
    env_file: ./docker/alert-service/env
    ports:
      - 127.0.0.1:8084:8084
    restart: always
  sql-database:
    build: ./docker/sql-database/
    volumes:
      - sql-database:/var/lib/mysql/
    ports:
      - 127.0.0.1:3306:3306
    env_file: ./docker/sql-database/env
    restart: always

volumes:
  sql-database:
